In [41]:
import pandas as pd
import numpy as np

path = 'C:/Users/elris/Dropbox/FBA/2020MiraeAsset/woogie/종목변환.csv'
item_num = pd.read_csv(path)

path = 'C:/Users/elris/Dropbox/FBA/2020MiraeAsset/woogie/answer_sheet.csv'
answer_sheet = pd.read_csv(path)

path = 'C:/Users/elris/Dropbox/FBA/2020MiraeAsset/woogie/stocks.csv'
stocks = pd.read_csv(path, index_col = 0)

path = 'C:/Users/elris/Dropbox/FBA/2020MiraeAsset/woogie/trade_train.csv'
trade_train = pd.read_csv(path, index_col = 0)

In [80]:
len(set(stocks['종목번호']))

1087

In [42]:
item_num.head()

   종목번호  종목번호_원본
0     0  A000100
1     1  A000140
2     2  A000440
3     3  A000660
4     4  A000885

In [69]:
item_dict = dict(zip(item_num['종목번호_원본'], item_num['종목번호']))

In [72]:
len(item_dict)

133

In [82]:
item_dict.keys()

dict_keys(['A000100', 'A000140', 'A000440', 'A000660', 'A000885', 'A000990', 'A001510', 'A001520', 'A001840', 'A003000', 'A003010', 'A003490', 'A004020', 'A004370', 'A00499K', 'A005360', 'A005380', 'A005930', 'A005935', 'A006800', 'A007070', 'A007570', 'A007660', 'A007980', 'A008060', 'A008930', 'A009240', 'A009830', 'A010140', 'A010145', 'A010600', 'A010950', 'A011150', 'A011280', 'A011320', 'A012700', 'A014100', 'A015760', 'A017670', 'A018880', 'A019170', 'A021240', 'A023530', 'A023590', 'A025440', 'A025870', 'A028100', 'A030200', 'A030350', 'A032640', 'A032850', 'A033170', 'A033250', 'A034730', 'A035420', 'A035720', 'A036540', 'A036570', 'A036930', 'A037330', 'A038540', 'A042670', 'A044960', 'A047050', 'A047400', 'A047820', 'A049080', 'A050120', 'A051780', 'A051910', 'A052260', 'A052900', 'A058110', 'A058400', 'A060370', 'A065170', 'A066430', 'A067080', 'A068270', 'A082270', 'A086520', 'A089150', 'A089980', 'A090410', 'A090430', 'A091990', 'A095610', 'A096530', 'A096770', 'A102940', 'A105560', 'A105840', 'A114120', 'A115180', 'A123010', 'A131390', 'A133750', 'A139050', 'A139130', 'A141020', 'A158430', 'A166090', 'A174880', 'A193250', 'A195440', 'A196490', 'A200670', 'A200780', 'A206560', 'A215100', 'A217730', 'A218410', 'A222080', 'A225430', 'A228760', 'A234100', 'A235980', 'A236200', 'A239340', 'A242040', 'A248170', 'A257370', 'A263720', 'A272210', 'A281820', 'A282880', 'A285130', 'A288620', 'A290550', 'A307930', 'A317530', 'A317870', 'A353810'])

In [74]:
len(set(top5_score.columns))

1066

In [84]:
top5_score = top5_score[item_dict.keys()]

In [43]:
group_num = pd.DataFrame(columns=['그룹명','그룹번호'])

In [44]:
group_num['그룹명'] = answer_sheet['그룹명']

In [45]:
group_num['그룹번호'] = range(1,49)

In [46]:
group_num.head()

     그룹명  그룹번호
0  MAD01     1
1  MAD02     2
2  MAD03     3
3  MAD04     4
4  MAD05     5

In [66]:
group_dict = dict(zip(group_num['그룹명'], group_num['그룹번호']))

In [67]:
group_dict

{'MAD01': 1,
 'MAD02': 2,
 'MAD03': 3,
 'MAD04': 4,
 'MAD05': 5,
 'MAD06': 6,
 'MAD07': 7,
 'MAD08': 8,
 'MAD09': 9,
 'MAD10': 10,
 'MAD11': 11,
 'MAD12': 12,
 'MAD13': 13,
 'MAD14': 14,
 'MAD15': 15,
 'MAD16': 16,
 'MAD17': 17,
 'MAD18': 18,
 'MAD19': 19,
 'MAD20': 20,
 'MAD21': 21,
 'MAD22': 22,
 'MAD23': 23,
 'MAD24': 24,
 'MAD25': 25,
 'MAD26': 26,
 'MAD27': 27,
 'MAD28': 28,
 'MAD29': 29,
 'MAD30': 30,
 'MAD31': 31,
 'MAD32': 32,
 'MAD33': 33,
 'MAD34': 34,
 'MAD35': 35,
 'MAD36': 36,
 'MAD37': 37,
 'MAD38': 38,
 'MAD39': 39,
 'MAD40': 40,
 'MAD41': 41,
 'MAD42': 42,
 'MAD43': 43,
 'MAD44': 44,
 'MAD45': 45,
 'MAD46': 46,
 'MAD47': 47,
 'MAD48': 48}

In [85]:
top5_score

,A000100,A000140,A000440,A000660,A000885,A000990,A001510,A001520,A001840,A003000,...,A272210,A281820,A282880,A285130,A288620,A290550,A307930,A317530,A317870,A353810
MAD01,0.00000,0.0,0.0,0.436554,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD02,0.00000,0.0,0.0,0.096347,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD03,0.00000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.084402,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD04,0.00000,0.0,0.0,0.422485,0.0,0.0,0.0,0.0,0.0,0.039900,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD05,0.00000,0.0,0.0,0.019020,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD06,0.00000,0.0,0.0,0.293457,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD07,0.00000,0.0,0.0,0.068816,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD08,0.00000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.054702,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD09,0.00000,0.0,0.0,0.095301,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD10,0.00000,0.0,0.0,0.014554,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD11,0.00000,0.0,0.0,0.370683,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD12,0.04029,0.0,0.0,0.057408,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD13,0.00000,0.0,0.0,0.009703,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD14,0.00000,0.0,0.0,0.091537,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD15,0.00000,0.0,0.0,0.098418,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD16,0.00000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD17,0.00000,0.0,0.0,0.367858,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD18,0.00000,0.0,0.0,0.381180,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD19,0.00000,0.0,0.0,0.122012,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD20,0.00000,0.0,0.0,0.109014,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD21,0.00000,0.0,0.0,0.142574,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD22,0.00000,0.0,0.0,0.014554,0.0,0.0,0.0,0.0,0.0,0.020000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD23,0.00000,0.0,0.0,0.366398,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD24,0.00000,0.0,0.0,0.044156,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.009415,0.0,0.0,0.0,0.0,0.000000,0.0
MAD25,0.00000,0.0,0.0,0.182970,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD26,0.00000,0.0,0.0,0.122675,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD27,0.00000,0.0,0.0,0.233875,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD28,0.00000,0.0,0.0,0.067833,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD29,0.00000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD30,0.00000,0.0,0.0,0.019602,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD31,0.00000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD32,0.00000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.039204,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.042795,0.0
MAD33,0.00000,0.0,0.0,0.459074,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD34,0.00000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD35,0.00000,0.0,0.0,0.415509,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD36,0.00000,0.0,0.0,0.273108,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD37,0.00000,0.0,0.0,0.052358,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD38,0.00000,0.0,0.0,0.144062,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD39,0.00000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD40,0.00000,0.0,0.0,0.019602,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD41,0.00000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.049801,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD42,0.00000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.030000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD43,0.00000,0.0,0.0,0.385742,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD44,0.00000,0.0,0.0,0.247230,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD45,0.00000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD46,0.00000,0.0,0.0,0.374645,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD47,0.00000,0.0,0.0,0.108018,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0
MAD48,0.00000,0.0,0.0,0.142634,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0

In [88]:
score_to_train = pd.DataFrame(columns=['그룹번호','종목번호','가중점수'])

In [51]:
score_to_train

Empty DataFrame
Columns: [그룹번호, 종목번호, 가중점수]
Index: []

In [47]:
path = 'C:/Users/elris/Dropbox/FBA/top5_score_0.01.csv'
top5_score = pd.read_csv(path, index_col = 0)

In [37]:
group = top5_score.index[0]

In [38]:
item = top5_score.columns[0]

In [39]:
score = top5_score.iloc[0][0]

In [36]:
len(top5_score.index)

48

In [52]:
top_dict = {'종목번호' : item, '그룹번호' : group, '가중점수' : score}

In [54]:
score_to_train.append(top_dict, ignore_index = True)

    그룹번호     종목번호  가중점수
0  MAD01  A049480   0.0

In [89]:
for i in range(len(top5_score.index)) : 
    for j in range(len(top5_score.columns)) : 
        group = group_dict[top5_score.index[i]]
        item = item_dict[top5_score.columns[j]]
        score = top5_score.iloc[i][j]
        top_dict = {'종목번호' : item, '그룹번호' : group, '가중점수' : score}
        score_to_train = score_to_train.append(top_dict, ignore_index = True)

In [90]:
score_to_train

      그룹번호   종목번호      가중점수
0      1.0    0.0  0.000000
1      1.0    1.0  0.000000
2      1.0    2.0  0.000000
3      1.0    3.0  0.436554
4      1.0    4.0  0.000000
...    ...    ...       ...
6379  48.0  128.0  0.000000
6380  48.0  129.0  0.000000
6381  48.0  130.0  0.000000
6382  48.0  131.0  0.000000
6383  48.0  132.0  0.000000

[6384 rows x 3 columns]

In [93]:
score_to_train.to_csv('C:/Users/elris/Dropbox/FBA/score_to_train_0.01.csv', index=True)